version: "3.8"
services:
  # Discord bot
  articuno:
    build: ./articuno
    restart: unless-stopped
    env_file:
      - ./articuno/.env
    ports:
      - '80:80'
    volumes:
      - /balti/node_modules
  # zapdos(nextjs? flutter? react native?):
  #   build: ./zapdos
  #   env_file:
  #     - ./zapdos/.env
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - /zapdos/node_modules
  #   stdin_open: true
  #   tty: true
# moltres (elixir/phoenix):
  #   build: ./moltres
  #   env_file:
  #     - ./moltres/.env
  #   ports:
  #     - 4000:4000
  #       external:internal
  #   restart: unless-stopped
  #   depends_on:
  #     - bot
  #     - client