version: "3.8"
services:
  # api:
  #   build: ./api
  #   env_file:
  #     - ./api/.env
  #   ports:
  #     - 4000:4000
  #       external:internal
  #   volumes:
  #     - /api/node_modules
  #   depends_on:
  #     - bot
  #     - client
  bot:
    build: ./bot
    env_file:
      - ./bot/.env
    ports:
      - '80:80'
    volumes:
      - /balti/node_modules
  # client:
  #   build: ./client
  #   env_file:
  #     - ./client/.env
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - /client/node_modules
  #   stdin_open: true
  #   tty: true
