import type { NextPage } from 'next'
import Head from 'next/head'

import Layout from '../components/layout'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Aozora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo autem praesentium quia reiciendis molestias perspiciatis deserunt officiis, id sapiente veniam quasi maxime exercitationem facere enim repellat unde dolores labore doloribus dolor vitae, consectetur minus iusto. Soluta nulla doloremque tempora nisi.
      </div>
    </>
  )
}

export default Home
